---
- name: "copy kube master certs"
  hosts: masters
  become: yes
  tasks:
    - name: "Copy etcd ca.crt"
      copy:
        src: /home/ubuntu/ca.crt
        dest: /var/lib/kubernetes/ca.crt
        remote_src: yes
        owner: root
        group: root
        mode: '0600'

    - name: "Copy etcd ca.key"
      copy:
        src: /home/ubuntu/ca.key
        dest: /var/lib/kubernetes/ca.key
        remote_src: yes
        owner: root
        group: root
        mode: '0600'

    - name: "Copy etcd kube-apiserver.crt"
      copy:
        src: /home/ubuntu/kube-apiserver.crt
        dest: /var/lib/kubernetes/kube-apiserver.crt
        remote_src: yes
        owner: root
        group: root
        mode: '0600'

    - name: "Copy etcd kube-apiserver.key"
      copy:
        src: /home/ubuntu/kube-apiserver.key
        dest: /var/lib/kubernetes/kube-apiserver.key
        remote_src: yes
        owner: root
        group: root
        mode: '0600'

    - name: "Copy etcd service-account.key"
      copy:
        src: /home/ubuntu/service-account.key
        dest: /var/lib/kubernetes/service-account.key
        remote_src: yes
        owner: root
        group: root
        mode: '0600'

    - name: "Copy etcd service-account.crt"
      copy:
        src: /home/ubuntu/service-account.crt
        dest: /var/lib/kubernetes/service-account.crt
        remote_src: yes
        owner: root
        group: root
        mode: '0600'

    - name: "Copy etcd etcd-server.key"
      copy:
        src: /home/ubuntu/etcd-server.key
        dest: /var/lib/kubernetes/etcd-server.key
        remote_src: yes
        owner: root
        group: root
        mode: '0600'

    - name: "Copy etcd etcd-server.crt"
      copy:
        src: /home/ubuntu/etcd-server.crt
        dest: /var/lib/kubernetes/etcd-server.crt
        remote_src: yes
        owner: root
        group: root
        mode: '0600'

    - name: "Copy etcd encryption-config.yaml"
      copy:
        src: /home/ubuntu/encryption-config.yaml
        dest: /var/lib/kubernetes/encryption-config.yaml
        remote_src: yes
        owner: root
        group: root
        mode: '0600'


 # sudo cp ca.crt ca.key kube-apiserver.crt kube-apiserver.key \
 #   service-account.key service-account.crt \
 #   etcd-server.key etcd-server.crt \
 #   encryption-config.yaml /var/lib/kubernetes/